#!/bin/bash

docker_image=$1

if [[ -z $docker_image ]]
then
	echo "You must specify a docker image to run inside"
	exit 1
fi

set +e

# TODO: Add caches for other OSes and perhaps a way to only mount in specific OSes instead of all.
# Using -e instead of -d incase it is a symlink
[[ -e '/var/cache/pacman/pkg' ]] && CACHE="-v /var/cache/pacman/pkg:/var/cache/pacman/pkg" || CACHE=""

trap cleanup SIGINT SIGTERM
docker run --rm \
	   --interactive \
	   --entrypoint=/bin/bash \
           $CACHE \
	   $docker_image -c "script -c /bin/bash <(/dev/null)"
# Unable to get return code because script will exit with 0 and absorb any other return codes.
