#!/bin/bash
DOTFILES=~/dotfiles
PACMAN="zsh git"
AUR="vim-solarized-git dircolors-solarized-git"
MACPORT="zsh git-core"
LINUX=false

INST_AURA=`pacman -Q aura|grep -oE '[0-9]\.[0-9.]+(\-[0-9])?'`
PAC_AURA=`ls $DOTFILES/install-files/aura*|grep -oE '[0-9]\.[0-9.]+(\-[0-9])?'`
if [ "$INST_AURA" != "$PAC_AURA" ]; then
	echo "Old/missing aura detected."
	echo "Installing/updating aura"
	sudo pacman -U install-files/aura*
fi

echo "Copying dotfiles..."
rsync -a --exclude=install --exclude=install-files --exclude=.git $DOTFILES/.* ~/
#Check if running Arch Linux
echo "Verifying required packages are installed..."
if grep -vq "Arch Linux" /etc/os-release > /dev/null 2>&1; then
	LINUX=true
	for package in $PACMAN
	do
		pacman -Q $package > /dev/null 2>&1 || PACINST="$PACINST $package"
	done

	for package in $AUR
	do
		pacman -Q $package > /dev/null 2>&1 || AURINST="$AURINST $package"
	done
	[[ $PACINST == "" ]] || sudo pacman -S $PACINST
	[[ $AURINST == "" ]] || sudo aura -A $AURINST
	
#Check if running OS X
elif uname -a|grep -qi darwin > /dev/null 2>&1; then
	for package in $MACPORT
	do
		port installed|grep $package > /dev/null 2>&1 || MPINST="$MPINST $package"
	done
	[[ $MPINST == "" ]] || sudo port install $MPINST
	cp $DOTFILES/install-files/mac-gitconfig ~/.gitconfig
else
	echo "You are not using Arch Linux; You may have to install zsh, git, vim-solarized and droidsansmono-powerline manually"
	echo "Once you have; press enter to continue"
	read
fi

if [ "$LINUX" == "true" ]; then
	cp $DOTFILES/install-files/arch-gitconfig ~/.gitconfig
	echo "Copying fonts..."
	sudo cp $DOTFILES/install-files/fonts/OTF/* /usr/share/fonts/OTF/
fi

echo "Installing/updating oh-my-zsh..."
rm -rf ~/.oh-my-zsh
cd ~
tar zxf $DOTFILES/install-files/oh-my-zsh.tar.gz
cd ~/.oh-my-zsh
git reset --hard origin/master > /dev/null 2>&1
git pull > /dev/null 2>&1
rm -rf ~/.git

echo "Changing shell to ZSH..."
echo $SHELL|grep -q zsh || chsh -s `which zsh`
