#!/bin/bash

apps=(
	authy
	caprine
	copyclip
	fantastical
	firefox
	google-drive-file-stream
	iterm2
	notion
	omnifocus
	spectacle
	spotify
	slack
	sublime-text
	visual-studio-code
)

work_apps=(
	amazon-workdocs
	quip
)

install() {
	packages=("$@")
	existing_packages="$(brew cask list)"
	for package in "${packages[@]}"; do
		if ! [[ $existing_packages =~ $package ]]; then
			brew cask install $package
		fi
	done
}

install "${apps[@]}"

echo "Install work apps as well? (ctrl+c to exit)"
read
install "${work_apps[@]}"
