#!/bin/bash
PICTURESDIR="$HOME/Pictures"
LOG="$HOME/.$(basename "$(readlink -f "$0")").log"
PATH="$PATH:/usr/bin/vendor_perl"
#set -x

echo '' > "$LOG"

if ! which exiftool > /dev/null
then
	echo "exiftool not found!"
	exit 1
fi

while [ -n "$*" ]
do
	if ! echo $1 | grep -qE '\.(xmp|pp3)$'
	then
		if [[ ! -f "$1" ]]
		then
			echo "$1 is not a valid file! Skipping..."
		else
			if echo "$1" | grep -Eq '(pp3|xmp)$'
			then
				echo "Ignoring pp3/xmp: $1" >> "$LOG"
				echo '' >> "$LOG"
				shift
				continue
			fi
			echo "Sorting picture: $1"
			date=""
			ext=
			format="${1##*.}"
			case "$format" in
				jpg|JPG|cr2|CR2)
					date=$(exiftool "$1"|grep "Date/Time Original"|head -n1|awk '{print $4}'|sed 's/:/-/g')
					;;
				mp4|MP4)
					date=$(exiftool "$1"|grep "Media Create Date"|awk '{print $5}'|sed 's/:/-/g')
					;;
			esac

			source='exif'
			# Fallback to date modified if it cannot be found
			[[ -z $date ]] && date=${date:-$(stat "$1"|grep Modify|awk '{print $2}')} && source='mtime'

			outputdir=$PICTURESDIR/${date%%-*}/$date/

			echo "input: $1" >> "$LOG"
			echo "date: $date" >> "$LOG"
			echo "date source: $source" >> "$LOG"
			echo "outputdir: $outputdir" >> "$LOG"
			echo '' >> "$LOG"

			output=""$(basename "$1")""
			mkdir -p "$outputdir"
			mv "$1" "$outputdir/${output//:nopm:}"
			[[ -f ${1}.pp3 ]] && mv "${1}.pp3" "$outputdir/${output//:nopm:}.pp3"
			[[ -f ${1}.out.pp3 ]] && mv "${1}.out.pp3" "$outputdir/${output//:nopm:}.out.pp3"
			[[ -f ${1}.xmp ]] && mv "${1}.xmp" "$outputdir/${output//:nopm:}.xmp"
		fi
	fi
	shift
done
echo 'See log for more details.'
