#!/bin/bash

source ~/.config/waybar/scripts/generate-bar

cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')

bar=$(generate_bar "$cpu_usage")
echo "{\"text\": \" $bar\", \"tooltip\": \"CPU usage: ${cpu_usage%.*}%\"}"
