#!/bin/bash
#symlink flake8-python2 to flake8 so that vimrc works across various OSes
if [[ -x /usr/bin/flake8-python2 ]]
then
    ln -sf /usr/bin/flake8-python2 ~/.bin/flake8
else
    rm -f ~/.bin/flake8
fi

if uname | grep -i darwin
then
	if ! pip list 2>/dev/null | grep virtualenvwrapper &>/dev/null
	then
		pip install virtualenvwrapper
	fi
fi
