#!/bin/bash
defaults write com.googlecode.iterm2 AlternateMouseScroll -bool true

# Python packages
for package in virtualenvwrapper flake8
do
	if ! pip list 2>/dev/null | grep $package &>/dev/null
	then
		pip install $package
	fi
done

# Node packages
for package in jshint jsonlint
do
	if ! npm list -g $package &>/dev/null
	then
		npm install -g $package &>/dev/null
	fi
done
