#!/bin/bash
#symlink flake8-python2 to flake8 so that vimrc works across various OSes
if [[ -x /usr/bin/flake8-python2 ]]
then
    ln -sf /usr/bin/flake8-python2 ~/.bin/flake8
else
    rm -f ~/.bin/flake8
fi

if uname | grep -qi darwin
then
	defaults write com.googlecode.iterm2 AlternateMouseScroll -bool true

	for package in virtualenvwrapper flake8
	do
		if ! pip list 2>/dev/null | grep $package &>/dev/null
		then
			pip install $package
		fi
	done

	for package in jshint jsonlint
	do
		if ! npm list $package &>/dev/null
		then
			npm install $package &>/dev/null
		fi
	done
fi
