#!/bin/bash

sed -i '/Valloric\/YouCompleteMe/d' ~/.vimrc
sed -i '/g:jedi#completions_enabled/d' ~/.vimrc

grep -q '\.bin:' ~/.bashrc || echo 'export PATH=$HOME/.bin:$PATH' >> ~/.bashrc
grep -q 'EDITOR=' ~/.bashrc || echo 'export EDITOR=/usr/bin/vim' >> ~/.bashrc

# Update git to 2.x
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get install git
