#!/bin/bash
# Script to download AUR packages

if [[ $# == 0 ]]
then
	echo "You must provide a package name!"
	exit 1
fi

if [[ $1 == '--help' ]]
then
	echo "USAGE: $(basename $0) package 1 [package 2] [package N]"
	exit 0
fi

[[ $(uname -m) == "armv7l" ]] && yaourt=1

packages=$@

if [[ ! -z "$yaourt" ]]; then
	for pkg in $packages
	do
		rm -rf $pkg
		yaourt -G $pkg 2> /dev/null
	done

else
	startdir=$(pwd)
	tmp=$(mktemp -d)
	[[ $? != 0 ]] && echo "An error has occurred while creating a temp directory! Aborting..." && exit 1
	cd $tmp
	aura -Aw $packages
	for i in $packages
	do
		cd "$tmp"
		test=$(ls $i*)
		if [[ -z $test ]]
		then
			echo "Package $i was not found"
		else
			tar xf "$tmp/$i.tar.gz"
			rm -rf "$tmp/$i.tar.gz"
		fi
	done

	[[ -z "$2" ]] && [[ -z "$test" ]] && exit 1
	mv $tmp/* "$startdir"
	rm -rf "$tmp"
fi
